# Generated by Django 5.1.3 on 2024-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_messages', to='api.group'),
        ),
    ]
